"""Configuration for geometric visualization."""

from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

from src.common.base_schema import BaseSchema


# =============================================================================
# Memory Optimization Constants
# =============================================================================

# Data type for activations (float32 = 50% memory savings vs float64)
ACTIVATION_DTYPE = np.float32

# Storage dtypes a run may pick for the activations it writes to disk. float16
# halves the run's disk footprint and is enough for geometry, but every analysis
# artifact stays float32 (see ACTIVATION_DTYPE).
STORAGE_DTYPES: dict[str, type] = {"float32": np.float32, "float16": np.float16}
DEFAULT_STORAGE_DTYPE = "float32"

# Components a target may name, in TransformerLens hook terms.
VALID_COMPONENTS = ("resid_pre", "resid_mid", "resid_post", "mlp_out", "attn_out")

# Buffer size for streaming extraction (samples to accumulate before flushing to disk)
# Higher = fewer disk writes but more memory; Lower = more disk writes but less memory
EXTRACTION_BUFFER_SIZE = 100

# Buffer size for streaming analysis (targets to process before GC)
ANALYSIS_GC_INTERVAL = 50

# Number of PCA components to store (reduces disk usage)
# Set to None to store all computed components
MAX_STORED_PCA_COMPONENTS = 20

# Whether to use compressed numpy storage (.npz vs .npy)
# Compressed is smaller on disk but slower to load
USE_COMPRESSED_STORAGE = False

# Plotting batch sizes
PLOT_GC_INTERVAL = 20  # GC after every N target groups
MAX_TRAJECTORY_SAMPLES = 200  # Max samples to plot in trajectory (for clarity)


# =============================================================================
# Semantic Positions
# =============================================================================
# Semantic positions are dynamically generated by SamplePositionMapping.build()
# based on the prompt format. See common/semantic_positions.py for canonical lists.



# =============================================================================
# Target Specification
# =============================================================================

@dataclass(slots=True)
class TargetSpec:
    """Specification for an activation extraction target.

    Uses __slots__ for reduced memory overhead.

    Attributes:
        layer: Transformer layer index
        component: Component type (resid_pre, resid_post, mlp_out, attn_out)
        position: Semantic position type (dynamically generated by SamplePositionMapping)
    """

    layer: int
    component: str
    position: str

    def __post_init__(self):
        if self.component not in VALID_COMPONENTS:
            raise ValueError(f"Invalid component: {self.component}")

    @property
    def key(self) -> str:
        """Unique key for this target.

        Format: L{layer}_{component}_{position}
        Example: L21_resid_post_response_choice, L13_resid_pre_short_term_reward
        """
        return f"L{self.layer}_{self.component}_{self.position}"

    @property
    def hook_name(self) -> str:
        """TransformerLens hook name."""
        patterns = {
            "resid_pre": f"blocks.{self.layer}.hook_resid_pre",
            "resid_mid": f"blocks.{self.layer}.hook_resid_mid",
            "resid_post": f"blocks.{self.layer}.hook_resid_post",
            "mlp_out": f"blocks.{self.layer}.hook_mlp_out",
            "attn_out": f"blocks.{self.layer}.hook_attn_out",
        }
        return patterns[self.component]

    def __repr__(self) -> str:
        return self.key


# =============================================================================
# Run Scope
# =============================================================================


@dataclass
class RunScope(BaseSchema):
    """What one run extracts: the layers, components and positions it targets.

    A run used to inherit the module constants in geometry_utils, which were
    written for a 36-layer model and for the full position schema. Carrying the
    scope on the config instead lets a run be projected onto another model depth
    and restricted to the change-of-turn window, and lets downstream analysis
    read the actual target set out of config.json.

    Attributes:
        layers: Transformer layer indices to extract
        components: Component names (see TargetSpec for the valid set)
        positions: Semantic position names
        dtype: Storage dtype for the activation files this run writes
    """

    layers: list[int] = field(default_factory=list)
    components: list[str] = field(default_factory=list)
    positions: list[str] = field(default_factory=list)
    dtype: str = DEFAULT_STORAGE_DTYPE

    def __post_init__(self):
        if self.dtype not in STORAGE_DTYPES:
            raise ValueError(
                f"Invalid storage dtype: {self.dtype} "
                f"(valid: {sorted(STORAGE_DTYPES)})"
            )
        invalid = [c for c in self.components if c not in VALID_COMPONENTS]
        if invalid:
            raise ValueError(
                f"Invalid components: {invalid} (valid: {list(VALID_COMPONENTS)})"
            )

    @property
    def numpy_dtype(self) -> type:
        """Numpy dtype the extractor casts activations to before saving."""
        return STORAGE_DTYPES[self.dtype]

    @property
    def n_targets(self) -> int:
        return len(self.layers) * len(self.components) * len(self.positions)

    def targets(self) -> list[TargetSpec]:
        """Expand the scope into one target per layer/component/position."""
        return [
            TargetSpec(layer=layer, component=component, position=position)
            for layer in self.layers
            for component in self.components
            for position in self.positions
        ]


# =============================================================================
# Pipeline Configuration
# =============================================================================

@dataclass
class GeometryConfig:
    """Configuration for geometric visualization pipeline.

    Attributes:
        scope: Layers, components, positions and storage dtype of this run
        targets: List of activation extraction targets (derived from scope
            when not given explicitly)
        output_dir: Output directory for results
        model: Model identifier
        seed: Random seed for reproducibility
        max_samples: Maximum number of samples to use (None = all)
        n_pca_components: Number of PCA components to compute
        dataset_cfg: Dataset configuration dict (defaults to GEOMETRY_CFG)

        # Memory optimization settings
        extraction_buffer_size: Samples to buffer before flushing to disk
        use_compressed_storage: Use compressed .npz files (slower but smaller)
    """

    scope: RunScope = field(default_factory=RunScope)
    targets: list[TargetSpec] = field(default_factory=list)
    output_dir: Path = field(default_factory=lambda: Path("out/geometry"))
    model: str = ""
    seed: int = 42
    max_samples: int | None = None
    n_pca_components: int = 50
    dataset_cfg: dict | None = None

    # Memory optimization settings
    extraction_buffer_size: int = EXTRACTION_BUFFER_SIZE
    use_compressed_storage: bool = USE_COMPRESSED_STORAGE

    def __post_init__(self):
        if isinstance(self.output_dir, str):
            self.output_dir = Path(self.output_dir)
        # A scope is the compact form of a target list, so expand it here and
        # keep one source of truth for what the run extracts.
        if not self.targets:
            self.targets = self.scope.targets()

    @classmethod
    def from_dict(cls, d: dict) -> "GeometryConfig":
        """Create config from dictionary.

        All required fields must be present - missing keys will raise KeyError.
        """
        targets = [
            TargetSpec(**t) if isinstance(t, dict) else t for t in d["targets"]
        ]
        return cls(
            scope=RunScope.from_dict(d["scope"]),
            targets=targets,
            output_dir=Path(d["output_dir"]),
            model=d["model"],
            seed=d["seed"],
            max_samples=d["max_samples"],
            n_pca_components=d["n_pca_components"],
            dataset_cfg=d["dataset_cfg"],
            extraction_buffer_size=d["extraction_buffer_size"],
            use_compressed_storage=d["use_compressed_storage"],
        )

    def to_dict(self) -> dict:
        """Convert to dictionary."""
        return {
            "scope": self.scope.to_dict(),
            "targets": [
                {"layer": t.layer, "component": t.component, "position": t.position}
                for t in self.targets
            ],
            "output_dir": str(self.output_dir),
            "model": self.model,
            "seed": self.seed,
            "max_samples": self.max_samples,
            "n_pca_components": self.n_pca_components,
            "dataset_cfg": self.dataset_cfg,
            "extraction_buffer_size": self.extraction_buffer_size,
            "use_compressed_storage": self.use_compressed_storage,
        }


# =============================================================================
# Target Generation
# =============================================================================

# Core semantic positions that should always be extracted
# These are the most important for understanding model behavior
CORE_POSITIONS = [
    # Response positions (where choice is decoded)
    "response_choice",
    "response_choice_prefix",
    # Time/reward values
    "time_horizon",
    "post_time_horizon",
    "left_time",
    "right_time",
    "left_reward",
    "right_reward",
    # Labels
    "left_label",
    "right_label",
    # Section tails (conclusions of each section)
    "situation_tail",
    "task_tail",
    "objective_tail",
    "action_tail",
    "format_tail",
    "options_tail",
    # Chat template
    "chat_suffix",
]


def generate_all_targets(
    layers: list[int],
    positions: list[str] | None = None,
    components: list[str] | None = None,
) -> list[TargetSpec]:
    """Generate comprehensive targets for all layer/position/component combinations.

    Args:
        layers: List of layer indices to extract
        positions: Semantic positions to extract (default: CORE_POSITIONS)
        components: Components to extract (default: all 4)

    Returns:
        List of TargetSpec for all combinations
    """
    if positions is None:
        positions = CORE_POSITIONS
    if components is None:
        components = ["resid_pre", "resid_post", "mlp_out", "attn_out"]

    targets = []
    for layer in layers:
        for component in components:
            for position in positions:
                targets.append(TargetSpec(layer, component, position))
    return targets


# =============================================================================
# Recommended Targets (curated subset - use generate_all_targets for comprehensive extraction)
# =============================================================================

RECOMMENDED_TARGETS = [
    # Response positions (where choice is decoded)
    TargetSpec(24, "resid_pre", "response_choice"),
    TargetSpec(21, "resid_post", "response_choice"),
    TargetSpec(21, "attn_out", "response_choice"),

    # Time horizon positions
    TargetSpec(21, "resid_post", "time_horizon"),
    TargetSpec(19, "mlp_out", "time_horizon"),

    # Option value positions (by presentation order)
    TargetSpec(21, "resid_post", "left_reward"),
    TargetSpec(21, "resid_post", "right_reward"),
    TargetSpec(21, "resid_post", "left_time"),
    TargetSpec(21, "resid_post", "right_time"),

    # Labels
    TargetSpec(13, "resid_post", "left_label"),
    TargetSpec(13, "resid_post", "right_label"),
]
